system:
 daytime: 2020-02-07T23:00 # utc observing time in isot format PARANAL time = UTC -3h
 # if divergence field is empty all div will be studied
 divergence:  #0.0022 #0.0022,0.008,0.0043,0.0022
 site: south
 configuration: baseline
 multiplicity_cut: 0

# if star field is empty a list of default stars will be studied
star: #pollux  #delta umi #elnath

header: True
verbose: True
outfile: FoV_test_south  #name only, no extension
