system:
 daytime: 2020-02-07T20:00 # utc observing time in isot format PARANAL time = UTC -3h
 divergence:  #0.0022 #0.0022,0.008,0.0043,0.0022    # if divergence field is empty all div will be studied
 site: north
 configuration: baseline #can be baseline or alpha
  multiplicity_cut: 0


star:            # if star field is empty a list of default stars will be studied
obs_hours: 8     #number of observing hours (don't leave empty)
header: True   #create header for txt file?
verbose: True
outfile: FoV_preliminary_north_20min  #name only, no extension
